// prisma/seed.ts
// Run: npx ts-node prisma/seed.ts
// Adds 20 sample leads so the dashboard works immediately

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const sampleLeads = [
  {
    source: 'google_maps',
    name: 'Sri Balaji Restaurants',
    city: 'Chennai',
    category: 'Restaurants',
    phone: '+91 9876543210',
    website: null,
    address: '45, T. Nagar, Chennai',
    rating: 4.1,
    reviewCount: 87,
    hasWebsite: false,
    websiteScore: null,
    aiScore: 80,
    aiLabel: 'hot',
    status: 'new',
    placeId: 'seed_001',
    needType: 'no_website',
    pitchMessage: 'Sri Balaji Restaurants has NO website — RED HOT lead. Losing customers daily.',
  },
  {
    source: 'google_maps',
    name: 'Modern Fitness Gym',
    city: 'Chennai',
    category: 'Gyms',
    phone: '+91 9876543211',
    website: 'http://modernfitness.in',
    address: '12, Anna Nagar, Chennai',
    rating: 3.8,
    reviewCount: 42,
    hasWebsite: true,
    websiteScore: 28,
    aiScore: 65,
    aiLabel: 'hot',
    status: 'new',
    placeId: 'seed_002',
    needType: 'redesign',
    pitchMessage: "Modern Fitness Gym's website is critically outdated. High redesign interest.",
  },
  {
    source: 'google_maps',
    name: 'Raj Dental Clinic',
    city: 'Bangalore',
    category: 'Clinics',
    phone: '+91 9876543212',
    website: null,
    address: '78, Koramangala, Bangalore',
    rating: 4.5,
    reviewCount: 210,
    hasWebsite: false,
    websiteScore: null,
    aiScore: 75,
    aiLabel: 'hot',
    status: 'contacted',
    placeId: 'seed_003',
    needType: 'no_website',
    pitchMessage: 'Raj Dental Clinic has NO website — 210 reviews but no online booking!',
  },
  {
    source: 'google_maps',
    name: 'Royal Properties',
    city: 'Chennai',
    category: 'Real Estate',
    phone: '+91 9876543213',
    website: 'https://royalprops.com',
    address: '3rd Floor, Nungambakkam, Chennai',
    rating: 3.2,
    reviewCount: 12,
    hasWebsite: true,
    websiteScore: 45,
    aiScore: 55,
    aiLabel: 'warm',
    status: 'new',
    placeId: 'seed_004',
    needType: 'seo',
    pitchMessage: 'Royal Properties needs SEO — low reviews + poor website score.',
  },
  {
    source: 'google_maps',
    name: 'New Star Hotel',
    city: 'Madurai',
    category: 'Hotels',
    phone: '+91 9876543214',
    website: null,
    address: '56, Main Road, Madurai',
    rating: 3.9,
    reviewCount: 33,
    hasWebsite: false,
    websiteScore: null,
    aiScore: 70,
    aiLabel: 'hot',
    status: 'new',
    placeId: 'seed_005',
    needType: 'no_website',
    pitchMessage: 'New Star Hotel has no website — losing bookings to OTA platforms.',
  },
  {
    source: 'google_maps',
    name: 'Classic Salon Studio',
    city: 'Bangalore',
    category: 'Salons',
    phone: '+91 9876543215',
    website: 'http://classicsalon.co.in',
    address: '22, Indiranagar, Bangalore',
    rating: 4.2,
    reviewCount: 156,
    hasWebsite: true,
    websiteScore: 38,
    aiScore: 50,
    aiLabel: 'warm',
    status: 'replied',
    placeId: 'seed_006',
    needType: 'redesign',
    pitchMessage: 'Classic Salon has a poor website — no online booking, no mobile view.',
  },
  {
    source: 'google_maps',
    name: 'Metro Coaching Centre',
    city: 'Coimbatore',
    category: 'Schools',
    phone: '+91 9876543216',
    website: null,
    address: '11, RS Puram, Coimbatore',
    rating: 4.7,
    reviewCount: 88,
    hasWebsite: false,
    websiteScore: null,
    aiScore: 80,
    aiLabel: 'hot',
    status: 'new',
    placeId: 'seed_007',
    needType: 'no_website',
    pitchMessage: 'Metro Coaching Centre has great reviews but NO website — massive opportunity.',
  },
  {
    source: 'google_maps',
    name: 'Lakshmi Jewellers',
    city: 'Chennai',
    category: 'Jewellery',
    phone: '+91 9876543217',
    website: 'http://lakshmijewels.com',
    address: '99, T Nagar, Chennai',
    rating: 4.0,
    reviewCount: 45,
    hasWebsite: true,
    websiteScore: 22,
    aiScore: 60,
    aiLabel: 'hot',
    status: 'new',
    placeId: 'seed_008',
    needType: 'redesign',
    pitchMessage: "Lakshmi Jewellers' website looks 2008-era — needs urgent redesign.",
  },
  {
    source: 'google_maps',
    name: 'Surya Auto Dealers',
    city: 'Pune',
    category: 'Auto Dealers',
    phone: '+91 9876543218',
    website: null,
    address: '7, Kothrud, Pune',
    rating: 3.6,
    reviewCount: 19,
    hasWebsite: false,
    websiteScore: null,
    aiScore: 65,
    aiLabel: 'hot',
    status: 'follow_up',
    placeId: 'seed_009',
    needType: 'no_website',
    pitchMessage: 'Surya Auto Dealers — no website in a high-competition niche.',
  },
  {
    source: 'google_maps',
    name: 'Elite Photography',
    city: 'Hyderabad',
    category: 'Photography Studios',
    phone: '+91 9876543219',
    website: 'https://elitephoto.in',
    address: '33, Banjara Hills, Hyderabad',
    rating: 4.8,
    reviewCount: 320,
    hasWebsite: true,
    websiteScore: 72,
    aiScore: 20,
    aiLabel: 'cold',
    status: 'closed',
    placeId: 'seed_010',
    needType: 'seo',
    pitchMessage: 'Elite Photography has a decent site but could improve local SEO.',
  },
];

async function main() {
  console.log('🌱 Seeding database with sample leads…');

  for (const lead of sampleLeads) {
    await prisma.lead.upsert({
      where: { placeId: lead.placeId },
      update: lead,
      create: lead,
    });
  }

  console.log(`✅ Seeded ${sampleLeads.length} sample leads`);
  console.log('🚀 Run: npm run dev and visit http://localhost:3000');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
